version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data2
  backend:
    image: xnmepa220/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend_media
  frontend:
    image: xnmepa220/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: xnmepa220/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - 9000:80
